// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds(name, url, created_by)
VALUES($1, $2, $3)
RETURNING id, added_at, name, url, created_by, last_fetched_at, created_at, updated_at
`

type CreateFeedParams struct {
	Name      string
	Url       string
	CreatedBy uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.Name, arg.Url, arg.CreatedBy)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.AddedAt,
		&i.Name,
		&i.Url,
		&i.CreatedBy,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllFeeds = `-- name: DeleteAllFeeds :exec
DELETE FROM feeds
WHERE id is not null
`

func (q *Queries) DeleteAllFeeds(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFeeds)
	return err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds
WHERE id = $1
`

func (q *Queries) DeleteFeed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, id)
	return err
}

const getAllFeeds = `-- name: GetAllFeeds :many
SELECT id, added_at, name, url, created_by, last_fetched_at, created_at, updated_at FROM feeds
`

func (q *Queries) GetAllFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.AddedAt,
			&i.Name,
			&i.Url,
			&i.CreatedBy,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFeedsWithUserName = `-- name: GetAllFeedsWithUserName :many
SELECT f.id, f.name as feedName, f.url, u.name as userName 
FROM feeds AS f
INNER JOIN users AS u
    ON f.created_by = u.id
`

type GetAllFeedsWithUserNameRow struct {
	ID       int64
	Feedname string
	Url      string
	Username sql.NullString
}

func (q *Queries) GetAllFeedsWithUserName(ctx context.Context) ([]GetAllFeedsWithUserNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeedsWithUserName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFeedsWithUserNameRow
	for rows.Next() {
		var i GetAllFeedsWithUserNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Feedname,
			&i.Url,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeed = `-- name: GetFeed :one
SELECT id, added_at, name, url, created_by, last_fetched_at, created_at, updated_at FROM feeds
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFeed(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.AddedAt,
		&i.Name,
		&i.Url,
		&i.CreatedBy,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedByUrl = `-- name: GetFeedByUrl :one
SELECT id, added_at, name, url, created_by, last_fetched_at, created_at, updated_at FROM feeds
WHERE url = $1 LIMIT 1
`

func (q *Queries) GetFeedByUrl(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByUrl, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.AddedAt,
		&i.Name,
		&i.Url,
		&i.CreatedBy,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextFeedToFetch = `-- name: GetNextFeedToFetch :one
SELECT id, added_at, name, url, created_by, last_fetched_at, created_at, updated_at FROM feeds
ORDER BY last_fetched_at ASC NULLS FIRST LIMIT 1
`

func (q *Queries) GetNextFeedToFetch(ctx context.Context) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedToFetch)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.AddedAt,
		&i.Name,
		&i.Url,
		&i.CreatedBy,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFeedFetched = `-- name: MarkFeedFetched :one
UPDATE feeds
SET last_fetched_at = $1, updated_at = $2
WHERE id = $3
RETURNING id, added_at, name, url, created_by, last_fetched_at, created_at, updated_at
`

type MarkFeedFetchedParams struct {
	LastFetchedAt sql.NullTime
	UpdatedAt     time.Time
	ID            int64
}

func (q *Queries) MarkFeedFetched(ctx context.Context, arg MarkFeedFetchedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, markFeedFetched, arg.LastFetchedAt, arg.UpdatedAt, arg.ID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.AddedAt,
		&i.Name,
		&i.Url,
		&i.CreatedBy,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
