// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID            int64
	AddedAt       time.Time
	Name          string
	Url           string
	CreatedBy     uuid.UUID
	LastFetchedAt sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Post struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PublishedAt sql.NullTime
	Title       string
	Description string
	Url         string
	CreatedBy   uuid.UUID
	FeedID      int64
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      sql.NullString
}

type UserFeed struct {
	UserID uuid.UUID
	FeedID int64
}
