// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserFeed = `-- name: CreateUserFeed :one
INSERT INTO user_feeds(user_id, feed_id)
VALUES($1, $2)
RETURNING user_id, feed_id
`

type CreateUserFeedParams struct {
	UserID uuid.UUID
	FeedID int64
}

func (q *Queries) CreateUserFeed(ctx context.Context, arg CreateUserFeedParams) (UserFeed, error) {
	row := q.db.QueryRowContext(ctx, createUserFeed, arg.UserID, arg.FeedID)
	var i UserFeed
	err := row.Scan(&i.UserID, &i.FeedID)
	return i, err
}

const deleteFeedForUser = `-- name: DeleteFeedForUser :exec
DELETE FROM user_feeds
WHERE user_id = $1 and feed_id = $2
`

type DeleteFeedForUserParams struct {
	UserID uuid.UUID
	FeedID int64
}

func (q *Queries) DeleteFeedForUser(ctx context.Context, arg DeleteFeedForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedForUser, arg.UserID, arg.FeedID)
	return err
}

const deleteWholeFeedForUser = `-- name: DeleteWholeFeedForUser :exec
DELETE from user_feeds
WHERE user_id = $1
`

func (q *Queries) DeleteWholeFeedForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWholeFeedForUser, userID)
	return err
}

const getFeedsForUser = `-- name: GetFeedsForUser :many
SELECT f.id, f.added_at, f.name, f.url, f.created_by, f.last_fetched_at, f.created_at, f.updated_at
FROM feeds AS f
INNER JOIN user_feeds AS uf
    ON f.id = uf.feed_id
WHERE uf.user_id = $1
`

func (q *Queries) GetFeedsForUser(ctx context.Context, userID uuid.UUID) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.AddedAt,
			&i.Name,
			&i.Url,
			&i.CreatedBy,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
